//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatShelter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public int Client { get; set; }
        public int Cat { get; set; }
        //public string FIO
        //{
        //    ger
        //    {
        //        return Users.Surname.toString()
        //    }
        //}
    
        public virtual Cats Cats { get; set; }
        public virtual Users Users { get; set; }
    }
}
