//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatShelter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cats
    {
        public int CatID { get; set; }
        public string CatName { get; set; }
        public decimal Age { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public int Color { get; set; }
        public int Breed { get; set; }
        public int Character { get; set; }
        public int Gender { get; set; }
    
        public virtual Breeds Breeds { get; set; }
        public virtual Characters Characters { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Genders Genders { get; set; }
    }
}
